baseurl = "https://minhduc2803.github.io/"
languageCode = "en-vi"
title = "Minh Duc"
paginate = 5
isqusshortname = "Minh Duc"
copyright = "@ VNG Fresher 2020"
pluralizelisttitles = false
theme = "casper"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[params]
  mainSections = ["post"]
  description = "Sometimes when I close my eyes, I can't see."
  cover = "images/background.jpg"
  author = "Minh Duc"
  authorlocation = "Ho Chi Minh, Viet Nam"
  authorbio= "A Software Development Fresher"
  logo = "images/logo.png"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml

  githubName = "minhduc2803"
  facebookName = "minduc97"
  # codepenName = ""
  # linkedinName = ""
  # stackoverflowId = ""
  # keybaseName = ""
  # flickrName = ""
  # instagramName = ""
  email = "ducnm8@vng.com.vn"
  # pinterestName = ""
  # googlePlusName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  hjsStyle = "default"
  

[Permalinks]
  post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
